library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://www.imdb.com/list/ls073043203/'
web <- read_html(url)
View(web)
hi=paths_allowed(url)
Name <- web %>% html_nodes('.lister-item-header a') %>% html_text()
View(Name)
Rating <- web %>% html_nodes('.ipl-rating-star.small .ipl-rating-star__rating') %>% html_text()
View(Rating)
genre<- web %>% html_nodes('.genre') %>% html_text()
View(genre)
data_ma= data.frame(Name,Rating,genre)
View(data_ma)
write.csv(data_ma,"cartoon-list.csv")
